title: Indians in Richmond BC
logo: /assets/img/logo.png
description: "Community hub for Indian businesses, events, resources, and connections in Richmond, BC."
show_downloads: false
google_analytics:
google_site_verification:
url: "https://indiansinrichmondbc.github.io"
baseurl: ""
lang: en-CA
timezone: America/Vancouver
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
